cliente:
    resource: "@ClienteBundle/Controller/"
    type:     annotation
    prefix:   /

proyecto:
    resource: "@ProyectoBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /usuarios/logout
