<?php

namespace ProyectoBundle\Repository;

/**
 * UsuariosVehiculosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosVehiculosRepository extends \Doctrine\ORM\EntityRepository
{
}
